language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build

before_deploy:
  - zip -r travis_test *
  - mkdir -p deploy
  - mv travis_test.zip deploy/travis_test.zip

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: mapgoblin-deploy-bucket
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  wait-until-deployed: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master